CRUD Species  & Добавление больше BaseClasses
TTG-Club/core-api pull request #23
Opened 2024-08-24 00:39 UTC by ProtectorRTD

**Базовые классы**
- Ренейминг одного из абстрастных классов
- Добавление нового абстракного класса

В результате благодаря им, можно выносить очень много кода. Так как просто наследуешь этот класс и все. Нам не нужен здесь полиморфизм, поэтому наследование в текущем случае подходит под наши условия.

**Создание Круд для Species**

Секьюрити и т.д, добавлю уже пост фактумом, когда разберемся, что там с фронтом

2024-08-24 10:55 UTC, Magistrus requested changes

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/character/Species.java
Creature Type: Humanoid тут по идее потом может быть другое
Size: Medium (about 4-7 feet tall) or Small (about 2-4 feet tall), chosen when you select this species
Speed: скорость в футтах
Traits:
- умение 1
- умение 2

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/character/Species.java
по идее можно еще отдельное поле для дальности темного зрения, чтобы мы могли по него фильтровать

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesSpecification.java
> +
не люблю пустые бессмысленные с точки разделения кода строки

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
По шаблону DI этот класс должен быть интерфейсом, и у него должен быть свой класс реализация

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesSpecification.java
идея вынести все в отдельный класс мне нравится, но хотелось бы сделать его и более универсальным, например с использованием дженерика 

У нас почти в всех сущностях будет:
* поиск 
* фильтрация по источникам
* фильтрация по дополнительным полям с условием AND или OR

Начать надо с SearchRequest и сделать так чтобы в него можно было бы добавить любое условия фильтрации без изменения класса, ну или в крайнем случае наследованием и переопределением.

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/dto/species/SpeciesResponse.java
> +    private Short page;
page относится к источнику, а не имени

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/mapper/species/SpeciesMapper.java
> +    SpeciesResponse speciesToSpeciesDTO(Species species);
toDto

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/mapper/species/SpeciesMapper.java
> +    Species speciesDTOToSpecies(SpeciesResponse speciesResponse);
toEntity

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/mapper/species/SpeciesMapper.java
именование методов маппинга должно быть универсальным во всех мапперах, чтобы не путаться потом

2024-08-24 10:55 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesSpecification.java
> +
лишняя пустая строка

2024-08-25 20:55 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
мне не нравится это, потому что тогда выходит создание лишнего класса, этот интерфейс не несет себе никакой логики, я если и встречал такой шаблон, то в очень старых проектах. Если и делать интерфейсы, то для полиморфизма или методов, чтобы соблюдался контракт

2024-08-31 10:58 UTC, closed without merging