Виды
TTG-Club/core-api pull request #24
Opened 2024-08-31 10:59 UTC by ProtectorRTD

- ООП для сущность
- Сервис
- Спецификация ООП

2024-09-01 20:36 UTC, Magistrus requested changes

2024-09-01 20:36 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/character/ClassService.java
> +//}
надо?

2024-09-01 20:36 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/character/ClassServiceImpl.java
> +//import java.util.Collection;
надо?

2024-09-01 20:36 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +    private static final SpeciesMapper speciesMapper = SpeciesMapper.INSTANCE;
тут мне кажется контракт именования констант нарушен

2024-09-01 20:36 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +                .orElseThrow(() -> new StorageException("Species not found with url: " + url));
у нас же есть специальное исключение для NotFound

2024-09-01 20:36 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +            Species updatedSpecies = speciesRepository.save(species);
тут у тебя будут появляется дубликаты, так как url может изменится, а он у нас ID

2024-09-01 20:36 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +    public SpeciesResponse save(SpeciesResponse speciesResponse) {
добавить @Transactional

2024-09-01 20:36 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +    public SpeciesResponse update(SpeciesResponse speciesResponse) {
добавить @Transactional

2024-09-01 20:36 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/specification/SpeciesSpecification.java
> +    private final List<SpecificationPart<Species>> specificationParts = new ArrayList<>();
capacity = 2

2024-09-17 18:08 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/controller/character/ClassController.java
> +//}
Это код твой и он оказался в моей ветке из-за мерджа, он не рабочий, я не сильно хотел разбираться где там что не работает, я хочу залить так, а потом ты мерджешь свой уже.

Не буду это сообщение писать к последующим комментарниям на счет комментированного кода, если режет глаза. Могу удалить в целом эти классы, потом веткой зальеш

2024-09-17 18:26 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/controller/MenuApiController.java
> +        menuResponse.setUrl(url);
Согласен, исправил.

2024-09-17 18:27 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/dto/engine/MenuResponse.java
> +@Data
Нет, не сильно в курсе, нюансов

2024-09-17 18:52 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +    private static final SpeciesMapper speciesMapper = SpeciesMapper.INSTANCE;
sonarLint ничего не говорит мне тут

2024-09-17 18:59 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/specification/SpeciesSpecification.java
> +    private final List<SpecificationPart<Species>> specificationParts = new ArrayList<>();
сейчас 2, в будущем больше же может быть

2024-09-20 07:35 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/controller/species/SpeciesController.java
> +@Tag(name = "API для Видов", description = "API для управления видами")
Эту аннотацию наверх перенести

2024-09-20 07:39 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/mapper/species/SpeciesMapper.java
> +            speciesResponse.setNameBasedDTO(new NameBasedDTO(
может тут для NameBaseDto билдер сделать?

2024-09-20 07:41 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/MenuService.java
> +@Transactional
наверное не нужно все методы сервиса оборачивать в транзакции

2024-09-20 07:43 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +    private static final SpeciesMapper speciesMapper = SpeciesMapper.INSTANCE;
По моему должно быть SPECIES_MAPPER

2024-09-20 07:55 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/service/MenuService.java
> +@Transactional
Согласен, исправлю

2024-09-20 07:55 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/mapper/species/SpeciesMapper.java
> +            speciesResponse.setNameBasedDTO(new NameBasedDTO(
Да, неплохая идея, добавлю

2024-09-26 14:00 UTC, merged