Многочисленные изменение в логике Species
TTG-Club/core-api pull request #26
Opened 2024-10-20 09:42 UTC by ProtectorRTD

- Добавленна поддержка всех полей и конвертов, которые необходимы
- Добавлены тестовый json + sql скрипт для правильного тестирование
- Добавлены некоторые тесты конверторы, в будущем необходимо покрыть большим количеством конверторов.
- Также в будущем, необходимо сделать лучше чистку Service layer там очень много методов, и выглядит немного как каша все, я бы разделил потом. Все что сохраняется оставил там, но все конверторы попытался бы ещё оптимизировать

В будущем следует ещё обратить внимание на количество итераций, кажется что можно оптимизировать.

В будущем планирую добавить диограмм, чтобы понять логику наследование / полиморфизма

2024-10-21 15:27 UTC, Magistrus requested changes

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/controller/species/SpeciesController.java
>  public class SpeciesController {
все таки во множественном числе будем?

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/controller/species/SpeciesController.java
> +    @Operation(summary = "Получить все связанные виды по URL подвига",
подвиДа

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/controller/species/SpeciesController.java
> +            description = "Возвращает список всех связанных видов, включая родительский вид и подвиды по указанному URL подвига.")
подвиДа

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/dto/species/CreateSpeciesDTO.java
> +        if (this.getSource() != null) {
заменить на тернтарку

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/base/FeatureBase.java
> +    @ManyToOne(cascade = CascadeType.ALL)
хм... а зачем тут полная каскадность?  Чтобы сохранять новый источник при добавлении фичи?

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/base/FeatureBase.java
> +    private Map<String, String> tags = new HashMap<>();
никогда не использовал на практике, надо будет чтобы ты рассказал как это работает

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/base/HasSourceEntity.java
> +public interface HasSourceEntity {
из название не совсем понятно, что это за интерфейс

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/book/Source.java
> +public class Source extends TimestampedEntity {
а чем источник отличается от книги?

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/species/Species.java
> +    @Cascade(org.hibernate.annotations.CascadeType.ALL)
а это зачем?

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +
лишняя пустая строка

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +            if (optionalBook.isPresent()) {
у Optional есть ifPresent и orElseThrow

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +                .toList();
можно сразу 
```
return speciesRepository.findByParent(parentSpecies)
                .stream()
                .map(species -> toDTO(species, true))
                .toList();
```

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +        List<Species> relatedSpecies = new ArrayList<>();
по моему тут можно задать capacity

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +            relatedSpecies.addAll(new ArrayList<>(subSpeciesList)); // Convert Collection to List
мне больше нравится через объединение стримов, тем более стрим дальше все равно создается

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +//                .toList();
Если больше не нужен код, удаляй его

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +        Converter.mapBaseDTOToEntityName(dto, species);
Есть правило написание абривиатур, так лучше читается

`mapBaseDtoToEntityName`

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +
лишняя строка

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +            List<Species> subSpecies = speciesResponse.getSubSpeciesUrls().stream()
тоже можно в одну строку

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +        if (features != null && !features.isEmpty()) {
CollectionUtils.isEmpty()

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/utills/Converter.java
> +    }
приватный конструктор можно через аннотацию Lombook делать

2024-10-21 15:27 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/utills/species/SpeciesFeatureConverter.java
> +    }
через ломбук

2024-11-04 21:07 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/model/base/FeatureBase.java
> +    @ManyToOne(cascade = CascadeType.ALL)
Хм, я не задумывался как раз над этим кейсом, я делал для удаление. Фича связаная с Расой, если расу удалили, зачем нам фича, которая принадлежит Виду, которого нету

2024-11-04 21:11 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/controller/species/SpeciesController.java
>  public class SpeciesController {
Specie, такого слова вроде как нету, правильно Species

2024-11-04 21:14 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/model/base/HasSourceEntity.java
> +public interface HasSourceEntity {
Есть ли у Сущности Source (источник) открыт для изменений нейминга

2024-11-04 21:15 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/model/book/Source.java
> +public class Source extends TimestampedEntity {
В источнике нету страниц, а вот в Source есть. Книга - PHB, но фича же может находиться на 5-ой странице, и на 10. Получается что у него будет таким образом указана страница и с какой книгой он связан. Мне эта реализация нравится больше чем на старом проекте. Из недостатков, что делать если текст находится на переходных страницах, не получится 2 страницы добавить в бд

2024-11-04 21:15 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/model/species/Species.java
> +    @Cascade(org.hibernate.annotations.CascadeType.ALL)
Согласен, бред написал, исправил. Каскадность тут нужна, чтобы если вид удалился, то зачем нам информация на каком странице он был написан

2024-11-04 21:26 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/service/species/SpeciesService.java
> +//                .toList();
В том-то и дело, что поиск все равно будет тут, а этот код так-то рабочий в какой-то мере, ему нужна просто актуальная поддержка. Поэтому и оставил, чтобы хоть помнить, как +- должно выглядеть

2024-11-07 15:36 UTC, Magistrus submitted a review, later dismissed

2024-11-07 15:37 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/base/FeatureBase.java
> +    @ManyToOne(cascade = CascadeType.ALL)
Я вообще думаю удаления быть не должно, скрыть от показа да, но полностью удалять с базы не правильно

2024-11-07 18:04 UTC, merged