Создание Источников / Книг
TTG-Club/core-api pull request #45
Opened 2024-12-10 23:35 UTC by ProtectorRTD

- Переделывание тегов
- Переделывание Service под Книги

2024-12-18 13:02 UTC, Magistrus requested changes

2024-12-18 13:02 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/service/TagService.java
> +
лишняя строка

2024-12-18 13:05 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/model/base/TagType.java
> +public enum TagType {
Именно так

2024-12-18 13:06 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/model/base/Translation.java
> +    private Integer translationYear;
А какой толк, от полной даты ? Могу, но просто важно же год, Никита не будет показывать месяц и день

2024-12-18 13:06 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/model/species/SpeciesFeature.java
> +    @ManyToMany
Он по стандарту, не лейзи ?

2024-12-18 13:09 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/dictionary/Size.java
> +			return null;
Хорошее, замечание

2024-12-18 13:10 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/dto/base/TranslationDTO.java
> +    private Integer year;
Окей, исправлю

2024-12-18 13:27 UTC, ProtectorRTD commented on src/main/java/club/ttg/dnd5/model/species/SpeciesFeature.java
> +    @ManyToMany
![image](https://github.com/user-attachments/assets/258cee7d-3bd1-4a55-925d-98f9084466c5)

2024-12-19 08:48 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/base/Translation.java
> +    private Integer translationYear;
Кроме отображение есть еще сортировка источников в фильтрах, чтобы самые свежие были в конце и если они вышли в один год, то сортировка не работает нормально

2024-12-19 08:49 UTC, Magistrus commented on src/main/java/club/ttg/dnd5/model/species/SpeciesFeature.java
> +    @ManyToMany
по дефолту вроде всегда был EAGER

2024-12-19 10:46 UTC, merged